/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2020-06-12 10:04:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\" />\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("        <meta name=\"description\" content=\"\" />\n");
      out.write("        <meta name=\"author\" content=\"\" />\n");
      out.write("        <title>Freelancer - Start Bootstrap Theme</title>\n");
      out.write("        <!-- Font Awesome icons (free version)-->\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v5.12.1/js/all.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <!-- Google fonts-->\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\n");
      out.write("        <link href=\"css/styles.css\" rel=\"stylesheet\" />\n");
      out.write("    </head>\n");
      out.write("    <body id=\"page-top\">\n");
      out.write("        <!-- Navigation-->\n");
      out.write("        <nav class=\"navbar navbar-expand-lg bg-secondary text-uppercase fixed-top\" id=\"mainNav\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <a class=\"navbar-brand js-scroll-trigger\" href=\"#page-top\">Start Bootstrap</a><button class=\"navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">Menu <i class=\"fas fa-bars\"></i></button>\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\n");
      out.write("                    <ul class=\"navbar-nav ml-auto\">\n");
      out.write("                        <li class=\"nav-item mx-0 mx-lg-1\"><a class=\"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger\" href=\"#portfolio\">Portfolio</a></li>\n");
      out.write("                        <li class=\"nav-item mx-0 mx-lg-1\"><a class=\"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger\" href=\"#about\">About</a></li>\n");
      out.write("                        <li class=\"nav-item mx-0 mx-lg-1\"><a class=\"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger\" href=\"#contact\">Contact</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <!-- Masthead-->\n");
      out.write("        <header class=\"masthead bg-primary text-white text-center\">\n");
      out.write("            <div class=\"container d-flex align-items-center flex-column\">\n");
      out.write("                <!-- Masthead Avatar Image--><img class=\"masthead-avatar mb-5\" src=\"assets/img/avataaars.svg\" alt=\"\" /><!-- Masthead Heading-->\n");
      out.write("                <h1 class=\"masthead-heading text-uppercase mb-0\">Start Bootstrap</h1>\n");
      out.write("                <!-- Icon Divider-->\n");
      out.write("                <div class=\"divider-custom divider-light\">\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\n");
      out.write("                </div>\n");
      out.write("                <!-- Masthead Subheading-->\n");
      out.write("                <p class=\"masthead-subheading font-weight-light mb-0\">Graphic Artist - Web Designer - Illustrator</p>\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("        <!-- Portfolio Section-->\n");
      out.write("        <section class=\"page-section portfolio\" id=\"portfolio\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <!-- Portfolio Section Heading-->\n");
      out.write("                <h2 class=\"page-section-heading text-center text-uppercase text-secondary mb-0\">Portfolio</h2>\n");
      out.write("                <!-- Icon Divider-->\n");
      out.write("                <div class=\"divider-custom\">\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\n");
      out.write("                </div>\n");
      out.write("                <!-- Portfolio Grid Items-->\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <!-- Portfolio Item 1-->\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal1\">\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\n");
      out.write("                            </div>\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/cabin.png\" alt=\"\" />\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Portfolio Item 2-->\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal2\">\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\n");
      out.write("                            </div>\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/cake.png\" alt=\"\" />\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Portfolio Item 3-->\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal3\">\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\n");
      out.write("                            </div>\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/circus.png\" alt=\"\" />\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Portfolio Item 4-->\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5 mb-lg-0\">\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal4\">\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\n");
      out.write("                            </div>\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/game.png\" alt=\"\" />\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Portfolio Item 5-->\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5 mb-md-0\">\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal5\">\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\n");
      out.write("                            </div>\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/safe.png\" alt=\"\" />\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Portfolio Item 6-->\n");
      out.write("                    <div class=\"col-md-6 col-lg-4\">\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal6\">\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\n");
      out.write("                            </div>\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/submarine.png\" alt=\"\" />\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!-- About Section-->\n");
      out.write("        <section class=\"page-section bg-primary text-white mb-0\" id=\"about\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <!-- About Section Heading-->\n");
      out.write("                <h2 class=\"page-section-heading text-center text-uppercase text-white\">About</h2>\n");
      out.write("                <!-- Icon Divider-->\n");
      out.write("                <div class=\"divider-custom divider-light\">\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\n");
      out.write("                </div>\n");
      out.write("                <!-- About Section Content-->\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-4 ml-auto\"><p class=\"lead\">Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional SASS stylesheets for easy customization.</p></div>\n");
      out.write("                    <div class=\"col-lg-4 mr-auto\"><p class=\"lead\">You can create your own custom avatar for the masthead, change the icon in the dividers, and add your email address to the contact form to make it fully functional!</p></div>\n");
      out.write("                </div>\n");
      out.write("                <!-- About Section Button-->\n");
      out.write("                <div class=\"text-center mt-4\">\n");
      out.write("                    <a class=\"btn btn-xl btn-outline-light\" href=\"https://startbootstrap.com/themes/freelancer/\"><i class=\"fas fa-download mr-2\"></i>Free Download!</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!-- Contact Section-->\n");
      out.write("        <section class=\"page-section\" id=\"contact\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <!-- Contact Section Heading-->\n");
      out.write("                <h2 class=\"page-section-heading text-center text-uppercase text-secondary mb-0\">Contact Me</h2>\n");
      out.write("                <!-- Icon Divider-->\n");
      out.write("                <div class=\"divider-custom\">\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\n");
      out.write("                </div>\n");
      out.write("                <!-- Contact Section Form-->\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-8 mx-auto\">\n");
      out.write("                        <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19.-->\n");
      out.write("                        <form id=\"contactForm\" name=\"sentMessage\" novalidate=\"novalidate\">\n");
      out.write("                            <div class=\"control-group\">\n");
      out.write("                                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\n");
      out.write("                                    <label>Name</label><input class=\"form-control\" id=\"name\" type=\"text\" placeholder=\"Name\" required=\"required\" data-validation-required-message=\"Please enter your name.\" />\n");
      out.write("                                    <p class=\"help-block text-danger\"></p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"control-group\">\n");
      out.write("                                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\n");
      out.write("                                    <label>Email Address</label><input class=\"form-control\" id=\"email\" type=\"email\" placeholder=\"Email Address\" required=\"required\" data-validation-required-message=\"Please enter your email address.\" />\n");
      out.write("                                    <p class=\"help-block text-danger\"></p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"control-group\">\n");
      out.write("                                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\n");
      out.write("                                    <label>Phone Number</label><input class=\"form-control\" id=\"phone\" type=\"tel\" placeholder=\"Phone Number\" required=\"required\" data-validation-required-message=\"Please enter your phone number.\" />\n");
      out.write("                                    <p class=\"help-block text-danger\"></p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"control-group\">\n");
      out.write("                                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\n");
      out.write("                                    <label>Message</label><textarea class=\"form-control\" id=\"message\" rows=\"5\" placeholder=\"Message\" required=\"required\" data-validation-required-message=\"Please enter a message.\"></textarea>\n");
      out.write("                                    <p class=\"help-block text-danger\"></p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <br />\n");
      out.write("                            <div id=\"success\"></div>\n");
      out.write("                            <div class=\"form-group\"><button class=\"btn btn-primary btn-xl\" id=\"sendMessageButton\" type=\"submit\">Send</button></div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!-- Footer-->\n");
      out.write("        <footer class=\"footer text-center\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <!-- Footer Location-->\n");
      out.write("                    <div class=\"col-lg-4 mb-5 mb-lg-0\">\n");
      out.write("                        <h4 class=\"text-uppercase mb-4\">Location</h4>\n");
      out.write("                        <p class=\"lead mb-0\">2215 John Daniel Drive<br />Clark, MO 65243</p>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Footer Social Icons-->\n");
      out.write("                    <div class=\"col-lg-4 mb-5 mb-lg-0\">\n");
      out.write("                        <h4 class=\"text-uppercase mb-4\">Around the Web</h4>\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#\"><i class=\"fab fa-fw fa-facebook-f\"></i></a><a class=\"btn btn-outline-light btn-social mx-1\" href=\"#\"><i class=\"fab fa-fw fa-twitter\"></i></a><a class=\"btn btn-outline-light btn-social mx-1\" href=\"#\"><i class=\"fab fa-fw fa-linkedin-in\"></i></a><a class=\"btn btn-outline-light btn-social mx-1\" href=\"#\"><i class=\"fab fa-fw fa-dribbble\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Footer About Text-->\n");
      out.write("                    <div class=\"col-lg-4\">\n");
      out.write("                        <h4 class=\"text-uppercase mb-4\">About Freelancer</h4>\n");
      out.write("                        <p class=\"lead mb-0\">Freelance is a free to use, MIT licensed Bootstrap theme created by <a href=\"http://startbootstrap.com\">Start Bootstrap</a>.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("        <!-- Copyright Section-->\n");
      out.write("        <section class=\"copyright py-4 text-center text-white\">\n");
      out.write("            <div class=\"container\"><small>Copyright © Your Website 2020</small></div>\n");
      out.write("        </section>\n");
      out.write("        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->\n");
      out.write("        <div class=\"scroll-to-top d-lg-none position-fixed\">\n");
      out.write("            <a class=\"js-scroll-trigger d-block text-center text-white rounded\" href=\"#page-top\"><i class=\"fa fa-chevron-up\"></i></a>\n");
      out.write("        </div>\n");
      out.write("        <!-- Portfolio Modals--><!-- Portfolio Modal 1-->\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"portfolioModal1Label\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog modal-xl\" role=\"document\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                        <span aria-hidden=\"true\"><i class=\"fas fa-times\"></i></span>\n");
      out.write("                    </button>\n");
      out.write("                    <div class=\"modal-body text-center\">\n");
      out.write("                        <div class=\"container\">\n");
      out.write("                            <div class=\"row justify-content-center\">\n");
      out.write("                                <div class=\"col-lg-8\">\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Log Cabin</h2>\n");
      out.write("                                    <!-- Icon Divider-->\n");
      out.write("                                    <div class=\"divider-custom\">\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <!-- Portfolio Modal - Image--><img class=\"img-fluid rounded mb-5\" src=\"assets/img/portfolio/cabin.png\" alt=\"\" /><!-- Portfolio Modal - Text-->\n");
      out.write("                                    <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\n");
      out.write("                                    <button class=\"btn btn-primary\" href=\"#\" data-dismiss=\"modal\"><i class=\"fas fa-times fa-fw\"></i>Close Window</button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Portfolio Modal 2-->\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"portfolioModal2Label\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog modal-xl\" role=\"document\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                        <span aria-hidden=\"true\"><i class=\"fas fa-times\"></i></span>\n");
      out.write("                    </button>\n");
      out.write("                    <div class=\"modal-body text-center\">\n");
      out.write("                        <div class=\"container\">\n");
      out.write("                            <div class=\"row justify-content-center\">\n");
      out.write("                                <div class=\"col-lg-8\">\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Tasty Cake</h2>\n");
      out.write("                                    <!-- Icon Divider-->\n");
      out.write("                                    <div class=\"divider-custom\">\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <!-- Portfolio Modal - Image--><img class=\"img-fluid rounded mb-5\" src=\"assets/img/portfolio/cake.png\" alt=\"\" /><!-- Portfolio Modal - Text-->\n");
      out.write("                                    <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\n");
      out.write("                                    <button class=\"btn btn-primary\" href=\"#\" data-dismiss=\"modal\"><i class=\"fas fa-times fa-fw\"></i>Close Window</button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Portfolio Modal 3-->\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"portfolioModal3Label\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog modal-xl\" role=\"document\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                        <span aria-hidden=\"true\"><i class=\"fas fa-times\"></i></span>\n");
      out.write("                    </button>\n");
      out.write("                    <div class=\"modal-body text-center\">\n");
      out.write("                        <div class=\"container\">\n");
      out.write("                            <div class=\"row justify-content-center\">\n");
      out.write("                                <div class=\"col-lg-8\">\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Circus Tent</h2>\n");
      out.write("                                    <!-- Icon Divider-->\n");
      out.write("                                    <div class=\"divider-custom\">\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <!-- Portfolio Modal - Image--><img class=\"img-fluid rounded mb-5\" src=\"assets/img/portfolio/circus.png\" alt=\"\" /><!-- Portfolio Modal - Text-->\n");
      out.write("                                    <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\n");
      out.write("                                    <button class=\"btn btn-primary\" href=\"#\" data-dismiss=\"modal\"><i class=\"fas fa-times fa-fw\"></i>Close Window</button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Portfolio Modal 4-->\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"portfolioModal4Label\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog modal-xl\" role=\"document\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                        <span aria-hidden=\"true\"><i class=\"fas fa-times\"></i></span>\n");
      out.write("                    </button>\n");
      out.write("                    <div class=\"modal-body text-center\">\n");
      out.write("                        <div class=\"container\">\n");
      out.write("                            <div class=\"row justify-content-center\">\n");
      out.write("                                <div class=\"col-lg-8\">\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Controller</h2>\n");
      out.write("                                    <!-- Icon Divider-->\n");
      out.write("                                    <div class=\"divider-custom\">\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <!-- Portfolio Modal - Image--><img class=\"img-fluid rounded mb-5\" src=\"assets/img/portfolio/game.png\" alt=\"\" /><!-- Portfolio Modal - Text-->\n");
      out.write("                                    <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\n");
      out.write("                                    <button class=\"btn btn-primary\" href=\"#\" data-dismiss=\"modal\"><i class=\"fas fa-times fa-fw\"></i>Close Window</button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Portfolio Modal 5-->\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"portfolioModal5Label\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog modal-xl\" role=\"document\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                        <span aria-hidden=\"true\"><i class=\"fas fa-times\"></i></span>\n");
      out.write("                    </button>\n");
      out.write("                    <div class=\"modal-body text-center\">\n");
      out.write("                        <div class=\"container\">\n");
      out.write("                            <div class=\"row justify-content-center\">\n");
      out.write("                                <div class=\"col-lg-8\">\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Locked Safe</h2>\n");
      out.write("                                    <!-- Icon Divider-->\n");
      out.write("                                    <div class=\"divider-custom\">\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <!-- Portfolio Modal - Image--><img class=\"img-fluid rounded mb-5\" src=\"assets/img/portfolio/safe.png\" alt=\"\" /><!-- Portfolio Modal - Text-->\n");
      out.write("                                    <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\n");
      out.write("                                    <button class=\"btn btn-primary\" href=\"#\" data-dismiss=\"modal\"><i class=\"fas fa-times fa-fw\"></i>Close Window</button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Portfolio Modal 6-->\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"portfolioModal6Label\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog modal-xl\" role=\"document\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                        <span aria-hidden=\"true\"><i class=\"fas fa-times\"></i></span>\n");
      out.write("                    </button>\n");
      out.write("                    <div class=\"modal-body text-center\">\n");
      out.write("                        <div class=\"container\">\n");
      out.write("                            <div class=\"row justify-content-center\">\n");
      out.write("                                <div class=\"col-lg-8\">\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Submarine</h2>\n");
      out.write("                                    <!-- Icon Divider-->\n");
      out.write("                                    <div class=\"divider-custom\">\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <!-- Portfolio Modal - Image--><img class=\"img-fluid rounded mb-5\" src=\"assets/img/portfolio/submarine.png\" alt=\"\" /><!-- Portfolio Modal - Text-->\n");
      out.write("                                    <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\n");
      out.write("                                    <button class=\"btn btn-primary\" href=\"#\" data-dismiss=\"modal\"><i class=\"fas fa-times fa-fw\"></i>Close Window</button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Bootstrap core JS-->\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("        <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("        <!-- Third party plugin JS-->\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js\"></script>\n");
      out.write("        <!-- Contact form JS-->\n");
      out.write("        <script src=\"assets/mail/jqBootstrapValidation.js\"></script>\n");
      out.write("        <script src=\"assets/mail/contact_me.js\"></script>\n");
      out.write("        <!-- Core theme JS-->\n");
      out.write("        <script src=\"js/scripts.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
