/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2020-06-29 07:44:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class matakuliah_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-\n");
      out.write("fit=no\">\n");
      out.write("\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\" content=\"\">\n");
      out.write("<title> Mata Kuliah</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Custom fonts for this template-->\n");
      out.write("<link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\"\n");
      out.write("type=\"text/css\">\n");
      out.write("<link\n");
      out.write("href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,6\n");
      out.write("00i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">\n");
      out.write("<!-- Custom styles for this template-->\n");
      out.write("<link href=\"css/sb-admin-2.min.css\" rel=\"stylesheet\">\n");
      out.write("<!-- The core Firebase JS SDK is always required and must be listed first -->\n");
      out.write("<script src=\"https://www.gstatic.com/firebasejs/7.15.0/firebase-app.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"https://www.gstatic.com/firebasejs/7.15.0/firebase-\n");
      out.write("database.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"https://www.gstatic.com/firebasejs/7.15.0/firebase-\n");
      out.write("firestore.js\"></script>\n");
      out.write("\n");
      out.write("<!-- TODO: Add SDKs for Firebase products that you want to use\n");
      out.write("https://firebase.google.com/docs/web/setup#available-libraries -->\n");
      out.write("\n");
      out.write("<script src=\"https://www.gstatic.com/firebasejs/7.15.0/firebase-\n");
      out.write("analytics.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  // Your web app's Firebase configuration\n");
      out.write("  var firebaseConfig = {\n");
      out.write("\t\t  apiKey: \"AIzaSyA1FTMo1CjlclESnYZleE2XCOCZD9csmLw\",\n");
      out.write("\t\t    authDomain: \"rmn-realtime-fb-b033c.firebaseapp.com\",\n");
      out.write("\t\t    databaseURL: \"https://rmn-realtime-fb-b033c.firebaseio.com\",\n");
      out.write("\t\t    projectId: \"rmn-realtime-fb-b033c\",\n");
      out.write("\t\t    storageBucket: \"rmn-realtime-fb-b033c.appspot.com\",\n");
      out.write("\t\t    messagingSenderId: \"624417790440\",\n");
      out.write("\t\t    appId: \"1:624417790440:web:b5ca39cc645f1a8d142c5d\",\n");
      out.write("\t\t    measurementId: \"G-Y15J0XQ9KV\"\n");
      out.write("  };\n");
      out.write("  // Initialize Firebase\n");
      out.write("  firebase.initializeApp(firebaseConfig);\n");
      out.write("  firebase.analytics();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body id=\"page-top\">\n");
      out.write("<!-- Page Wrapper -->\n");
      out.write("<div id=\"wrapper\">\n");
      out.write("<!-- Sidebar -->\n");
      out.write("<ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\"\n");
      out.write("id=\"accordionSidebar\">\n");
      out.write("<!-- Sidebar - Brand -->\n");
      out.write("<a class=\"sidebar-brand d-flex align-items-center justify-content-center\"\n");
      out.write("href=\"index.html\">\n");
      out.write("<div class=\"sidebar-brand-icon rotate-n-15\">\n");
      out.write("<i class=\"fas fa-laugh-wink\"></i>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"sidebar-brand-text mx-3\">SI Akademik</div>\n");
      out.write("</a>\n");
      out.write("<!-- Divider -->\n");
      out.write("<hr class=\"sidebar-divider my-0\">\n");
      out.write("<!-- Nav Item - Dashboard -->\n");
      out.write("<li class=\"nav-item\">\n");
      out.write("<a class=\"nav-link\" href=\"index.html\">\n");
      out.write("<i class=\"fas fa-fw fa-tachometer-alt\"></i>\n");
      out.write("<span>Dashboard</span></a>\n");
      out.write("</li>\n");
      out.write("<!-- Divider -->\n");
      out.write("<hr class=\"sidebar-divider\">\n");
      out.write("<!-- Heading -->\n");
      out.write("<div class=\"sidebar-heading\">\n");
      out.write("Menu\n");
      out.write("</div>\n");
      out.write("<!-- Nav Item - Charts -->\n");
      out.write("<li class=\"nav-item\">\n");
      out.write("<a class=\"nav-link\" href=\"matakuliah.jsp\">\n");
      out.write("<i class=\"fas fa-fw fa-chart-area\"></i>\n");
      out.write("<span>Mata Kuliah</span></a>\n");
      out.write("</li>\n");
      out.write("<!-- Nav Item - Tables -->\n");
      out.write("<li class=\"nav-item\">\n");
      out.write("<a class=\"nav-link\" href=\"dosen.jsp\">\n");
      out.write("<i class=\"fas fa-fw fa-table\"></i>\n");
      out.write("<span>Dosen</span></a>\n");
      out.write("</li>\n");
      out.write("<!-- Nav Item - Tables -->\n");
      out.write("<li class=\"nav-item\">\n");
      out.write("<a class=\"nav-link\" href=\"mengajar.jsp\">\n");
      out.write("<i class=\"fas fa-fw fa-table\"></i>\n");
      out.write("<span>Info</span></a>\n");
      out.write("</li>\n");
      out.write("</ul>\n");
      out.write("<!-- End of Sidebar -->\n");
      out.write("<!-- Content Wrapper -->\n");
      out.write("<div id=\"content-wrapper\" class=\"d-flex flex-column\">\n");
      out.write("<!-- Main Content -->\n");
      out.write("<div id=\"content\">\n");
      out.write("<!-- Topbar -->\n");
      out.write("<nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top\n");
      out.write("shadow\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Sidebar Toggle (Topbar) -->\n");
      out.write("<button id=\"sidebarToggleTop\" class=\"btn btn-link d-md-none rounded-circle\n");
      out.write("mr-3\">\n");
      out.write("<i class=\"fa fa-bars\"></i>\n");
      out.write("</button>\n");
      out.write("<!-- Topbar Navbar -->\n");
      out.write("<ul class=\"navbar-nav ml-auto\">\n");
      out.write("<div class=\"topbar-divider d-none d-sm-block\"></div>\n");
      out.write("<!-- Nav Item - User Information -->\n");
      out.write("<li class=\"nav-item dropdown no-arrow\">\n");
      out.write("<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\"\n");
      out.write("role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("<span class=\"mr-2 d-none d-lg-inline text-gray-600\n");
      out.write("small\">Administrator</span>\n");
      out.write("<img class=\"img-profile rounded-circle\"\n");
      out.write("src=\"https://source.unsplash.com/QAB-WJcbgJk/60x60\">\n");
      out.write("</a>\n");
      out.write("<!-- Dropdown - User Information -->\n");
      out.write("<div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\n");
      out.write("aria-labelledby=\"userDropdown\">\n");
      out.write("<a class=\"dropdown-item\" href=\"#\">\n");
      out.write("<i class=\"fas fa-user fa-sm fa-fw mr-2 text-gray-400\"></i>\n");
      out.write("Ubah Password\n");
      out.write("</a>\n");
      out.write("<div class=\"dropdown-divider\"></div>\n");
      out.write("\n");
      out.write("<a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\" data-\n");
      out.write("target=\"#logoutModal\">\n");
      out.write("\n");
      out.write("<i class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\n");
      out.write("Logout\n");
      out.write("</a>\n");
      out.write("</div>\n");
      out.write("</li>\n");
      out.write("</ul>\n");
      out.write("</nav>\n");
      out.write("<!-- End of Topbar -->\n");
      out.write("<!-- Begin Page Content -->\n");
      out.write("<div class=\"container-fluid\">\n");
      out.write("<!-- Page Heading -->\n");
      out.write("<h1 class=\"h3 mb-4 text-gray-800\">Mata Kuliah <a href=\"add_matakuliah.jsp\"\n");
      out.write("class=\"btn btn-success btn-user\">Tambah Baru</a></h1>\n");
      out.write("<hr/>\n");
      out.write("<form class=\"user\">\n");
      out.write("<div class=\"form-group\">\n");
      out.write("<input type=\"text\" class=\"form-control form-control-user\" id=\"uid\"\n");
      out.write("placeholder=\"ID\" readonly>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<div class=\"form-group row\">\n");
      out.write("<div class=\"col-sm-6 mb-3 mb-sm-0\">\n");
      out.write("<input type=\"text\" class=\"form-control form-control-user\"\n");
      out.write("id=\"kode\" placeholder=\"Kode Mata Kuliah\">\n");
      out.write("</div>\n");
      out.write("<div class=\"col-sm-6\">\n");
      out.write("<input type=\"number\" class=\"form-control form-control-user\"\n");
      out.write("id=\"sks\" placeholder=\"SKS\">\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"form-group\">\n");
      out.write("<input type=\"text\" class=\"form-control form-control-user\" id=\"nama\"\n");
      out.write("placeholder=\"Nama Mata Kuliah\">\n");
      out.write("</div>\n");
      out.write("<input type=\"button\" value=\"Update\" onclick=\"update_user();\"\n");
      out.write("class=\"btn btn-warning btn-user\" />\n");
      out.write("<input type=\"button\" value=\"Delete\" onclick=\"delete_user();\"\n");
      out.write("class=\"btn btn-danger btn-user\" />\n");
      out.write("<hr>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<div class=\"card shadow mb-4\">\n");
      out.write("<div class=\"card-header py-3\">\n");
      out.write("<h6 class=\"m-0 font-weight-bold text-primary\">Information</h6>\n");
      out.write("</div>\n");
      out.write("<div class=\"card-body\">\n");
      out.write("<div class=\"table-responsive\">\n");
      out.write("<table id=\"tb_matakuliah\" class=\"table table-bordered\" width=\"100%\"\n");
      out.write("cellspacing=\"0\">\n");
      out.write("\n");
      out.write("<tr>\n");
      out.write("<td>#ID</td>\n");
      out.write("<td>Kode</td>\n");
      out.write("<td>SKS</td>\n");
      out.write("<td>Nama</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<!-- /.container-fluid -->\n");
      out.write("</div>\n");
      out.write("<!-- End of Main Content -->\n");
      out.write("<!-- Footer -->\n");
      out.write("<footer class=\"sticky-footer bg-white\">\n");
      out.write("<div class=\"container my-auto\">\n");
      out.write("<div class=\"copyright text-center my-auto\">\n");
      out.write("<span>Copyright &copy; Your Website 2019</span>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</footer>\n");
      out.write("<!-- End of Footer -->\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!-- End of Content Wrapper -->\n");
      out.write("</div>\n");
      out.write("<!-- End of Page Wrapper -->\n");
      out.write("<!-- Scroll to Top Button-->\n");
      out.write("<a class=\"scroll-to-top rounded\" href=\"#page-top\">\n");
      out.write("<i class=\"fas fa-angle-up\"></i>\n");
      out.write("</a>\n");
      out.write("<!-- Logout Modal-->\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-\n");
      out.write("labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("\n");
      out.write("<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("<div class=\"modal-content\">\n");
      out.write("<div class=\"modal-header\">\n");
      out.write("<h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\n");
      out.write("\n");
      out.write("<button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-\n");
      out.write("label=\"Close\">\n");
      out.write("\n");
      out.write("<span aria-hidden=\"true\">×</span>\n");
      out.write("</button>\n");
      out.write("</div>\n");
      out.write("<div class=\"modal-body\">Select \"Logout\" below if you are ready to end your\n");
      out.write("current session.</div>\n");
      out.write("<div class=\"modal-footer\">\n");
      out.write("\n");
      out.write("<button class=\"btn btn-secondary\" type=\"button\" data-\n");
      out.write("dismiss=\"modal\">Cancel</button>\n");
      out.write("\n");
      out.write("<a class=\"btn btn-primary\" href=\"login.html\">Logout</a>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<!-- Bootstrap core JavaScript-->\n");
      out.write("<script src=\"vendor/jquery/jquery.min.js\"></script>\n");
      out.write("<script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<!-- Core plugin JavaScript-->\n");
      out.write("<script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("var tbMataKuliah = document.getElementById('tb_matakuliah');\n");
      out.write("var databaseRef = firebase.database().ref('matakuliah/');\n");
      out.write("var rowIndex = 1;\n");
      out.write("databaseRef.once('value', function(snapshot) {\n");
      out.write("snapshot.forEach(function(childSnapshot) {\n");
      out.write("var childKey = childSnapshot.key;\n");
      out.write("var childData = childSnapshot.val();\n");
      out.write("var row = tbMataKuliah.insertRow(rowIndex);\n");
      out.write("\n");
      out.write("var cellId = row.insertCell(0);\n");
      out.write("var cellKode = row.insertCell(1);\n");
      out.write("var cellSKS = row.insertCell(2);\n");
      out.write("var cellNama = row.insertCell(3);\n");
      out.write("cellId.appendChild(document.createTextNode(childKey));\n");
      out.write("cellKode.appendChild(document.createTextNode(childData.kode));\n");
      out.write("cellSKS.appendChild(document.createTextNode(childData.sks));\n");
      out.write("cellNama.appendChild(document.createTextNode(childData.nama));\n");
      out.write("rowIndex = rowIndex + 1;\n");
      out.write("});\n");
      out.write("\n");
      out.write("var table = document.getElementById(\"tb_matakuliah\");\n");
      out.write("var rows = table.getElementsByTagName(\"tr\");\n");
      out.write("for (i = 0; i < rows.length; i++) {\n");
      out.write("var currentRow = table.rows[i];\n");
      out.write("var createClickHandler = function(row) {\n");
      out.write("return function() {\n");
      out.write("\t\n");
      out.write("var cell1 = row.getElementsByTagName(\"td\")[0];\n");
      out.write("var cell2 = row.getElementsByTagName(\"td\")[1];\n");
      out.write("var cell3 = row.getElementsByTagName(\"td\")[2];\n");
      out.write("var cell4 = row.getElementsByTagName(\"td\")[3];\n");
      out.write("var id = cell1.innerHTML;\n");
      out.write("var kode = cell2.innerHTML;\n");
      out.write("var sks = cell3.innerHTML;\n");
      out.write("var nama = cell4.innerHTML;\n");
      out.write("\n");
      out.write("document.getElementById('uid').value = id;\n");
      out.write("document.getElementById('kode').value = kode;\n");
      out.write("document.getElementById('sks').value = sks;\n");
      out.write("document.getElementById('nama').value = nama;\n");
      out.write("};\n");
      out.write("};\n");
      out.write("currentRow.onclick = createClickHandler(currentRow);\n");
      out.write("}\n");
      out.write("});\n");
      out.write("function update_user(){\n");
      out.write("var kode = document.getElementById('kode').value;\n");
      out.write("var sks = document.getElementById('sks').value;\n");
      out.write("var nama = document.getElementById('nama').value;\n");
      out.write("var uid = document.getElementById('uid').value;\n");
      out.write("var data = {\n");
      out.write("kode: kode,\n");
      out.write("sks: sks,\n");
      out.write("nama: nama\n");
      out.write("}\n");
      out.write("var updates = {};\n");
      out.write("updates['/matakuliah/' + uid] = data;\n");
      out.write("firebase.database().ref().update(updates);\n");
      out.write("alert('mata kuliah updated successfully!');\n");
      out.write("reload_page();\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function delete_user(){\n");
      out.write("var uid = document.getElementById('uid').value;\n");
      out.write("firebase.database().ref().child('/matakuliah/' + uid).remove();\n");
      out.write("alert('mata kuliah deleted successfully!');\n");
      out.write("reload_page();\n");
      out.write("}\n");
      out.write("function reload_page(){\n");
      out.write("window.location.reload();\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
