/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2020-06-23 12:58:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<!-- Basic -->\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"utf-8\">\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\n");
      out.write("\t<!-- Mobile Metas -->\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("\t<!-- Site Metas -->\n");
      out.write("\t<title>Hava Contact</title>\n");
      out.write("\t<meta name=\"keywords\" content=\"\">\n");
      out.write("\t<meta name=\"description\" content=\"\">\n");
      out.write("\t<meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("\t<!-- Site Icons -->\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"../images/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("\t<link rel=\"apple-touch-icon\" href=\"../images/apple-touch-icon.png\">\n");
      out.write("\n");
      out.write("\t<!-- Bootstrap CSS -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\">\n");
      out.write("\t<!-- Site CSS -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/style.css\">\n");
      out.write("\t<!-- Responsive CSS -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/responsive.css\">\n");
      out.write("\t<!-- Custom CSS -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/custom.css\">\n");
      out.write("\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://unpkg.com/leaflet@1.6.0/dist/leaflet.css\" />\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body ng-app=\"validationApp\" ng-controller=\"mainController\">\n");
      out.write("<!-- The core Firebase JS SDK is always required and must be listed first -->\n");
      out.write("<script src=\"https://www.gstatic.com/firebasejs/7.15.4/firebase-app.js\"></script>\n");
      out.write("\n");
      out.write("<!-- TODO: Add SDKs for Firebase products that you want to use\n");
      out.write("     https://firebase.google.com/docs/web/setup#available-libraries -->\n");
      out.write("<script src=\"https://www.gstatic.com/firebasejs/7.15.4/firebase-analytics.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  // Your web app's Firebase configuration\n");
      out.write("  var firebaseConfig = {\n");
      out.write("    apiKey: \"AIzaSyAEJ-yMYB6RY8wqisHbrmculO2K8NiTSCQ\",\n");
      out.write("    authDomain: \"hava-recipe.firebaseapp.com\",\n");
      out.write("    databaseURL: \"https://hava-recipe.firebaseio.com\",\n");
      out.write("    projectId: \"hava-recipe\",\n");
      out.write("    storageBucket: \"hava-recipe.appspot.com\",\n");
      out.write("    messagingSenderId: \"190122979219\",\n");
      out.write("    appId: \"1:190122979219:web:2bf4915d4501ba5afe0266\",\n");
      out.write("    measurementId: \"G-M4CBVWWPC2\"\n");
      out.write("  };\n");
      out.write("  // Initialize Firebase\n");
      out.write("  firebase.initializeApp(firebaseConfig);\n");
      out.write("  firebase.analytics();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\t<!-- Start header -->\n");
      out.write("\t<header class=\"top-navbar\">\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"../index.html\">\n");
      out.write("\t\t\t\t\t<img src=\"../images/hava.png\" alt=\"Hava\" />\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbars-rs-food\"\n");
      out.write("\t\t\t\t\taria-controls=\"navbars-rs-food\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("\t\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbars-rs-food\">\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav ml-auto\">\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"../index.html\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"recipes.html\">Recipes</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"about.html\">About Us</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\" href=\"contact.html\">Contact</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\t</header>\n");
      out.write("\t<!-- End header -->\n");
      out.write("\n");
      out.write("\t<!-- Start All Pages -->\n");
      out.write("\t<div class=\"all-page-title page-breadcrumb\">\n");
      out.write("\t\t<div class=\"container text-center\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t\t<h1>Contact</h1>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- End All Pages -->\n");
      out.write("\n");
      out.write("\t<!-- Start Contact -->\n");
      out.write("\t<div class=\"contact-box\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t\t<div class=\"heading-title text-center\">\n");
      out.write("\t\t\t\t\t\t<h2>Contact</h2>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t\t<form name=\"userForm\" ng-submit=\"submitForm(userForm.$valid)\" novalidate>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\" ng-class=\"{ 'has-error' : userForm.name.$invalid && !userForm.name.$pristine }\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"name\">Name</label>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" class=\"form-control\" id=\"nama\"  ng-model=\"user.name\" required>\n");
      out.write("\t\t\t\t\t\t\t<small ng-show=\"userForm.name.$invalid && !userForm.name.$pristine\" class=\"help-block text-danger\">You\n");
      out.write("\t\t\t\t\t\t\t\tname is\n");
      out.write("\t\t\t\t\t\t\t\trequired.\n");
      out.write("\t\t\t\t\t\t\t</small>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\" ng-class=\"{ 'has-error' : userForm.email.$invalid && !userForm.email.$pristine }\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"email\">Email</label>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" class=\"form-control\" id=\"email\"  ng-model=\"user.email\">\n");
      out.write("\t\t\t\t\t\t\t<small ng-show=\"userForm.email.$invalid && !userForm.email.$pristine\" class=\"help-block text-danger\">Enter\n");
      out.write("\t\t\t\t\t\t\t\ta valid\n");
      out.write("\t\t\t\t\t\t\t\temail.\n");
      out.write("\t\t\t\t\t\t\t</small>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\" ng-class=\"{ 'has-error' : userForm.person.$invalid && !userForm.person.$pristine }\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"person\">Enter the Name of Recipe</label>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"person\" class=\"form-control\" id=\"menu\"  ng-model=\"user.person\">\n");
      out.write("\t\t\t\t\t\t\t<small ng-show=\"userForm.person.$invalid && !userForm.person.$pristine\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"help-block text-danger\">Enter\n");
      out.write("\t\t\t\t\t\t\t\ta valid\n");
      out.write("\t\t\t\t\t\t\t\tnumber\n");
      out.write("\t\t\t\t\t\t\t</small>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\"\n");
      out.write("\t\t\t\t\t\t\tng-class=\"{ 'has-error' : userForm.message.$invalid && !userForm.message.$pristine }\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"message\">Message</label>\n");
      out.write("\t\t\t\t\t\t\t<textarea type=\"text\" name=\"message\" class=\"form-control\" id=s\"komentar\"  ng-model=\"user.message\" required></textarea>\n");
      out.write("\t\t\t\t\t\t\t<small ng-show=\"userForm.message.$invalid && !userForm.message.$pristine\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"help-block text-danger\">Your Message\n");
      out.write("\t\t\t\t\t\t\t\tis required\n");
      out.write("\t\t\t\t\t\t\t</small>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" value=\"Save\" onclick=\"save_user();\" class=\"btn btn-red btn-lg btn-block text-uppercase\">SEND MESSAGE</button>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- End Contact -->\n");
      out.write("\n");
      out.write("\t<!-- Start Map -->\n");
      out.write("\t<div class=\"container-fluid mb-5\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col pb-2\">\n");
      out.write("\t\t\t\t<h1 class=\"text-center text-uppercase\">Office Location</h1>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col\">\n");
      out.write("\t\t\t\t<div id=\"map\" style=\"width: 100%; height: 300px;\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- End Map -->\n");
      out.write("\n");
      out.write("\t<!-- Start Contact info -->\n");
      out.write("\t<div class=\"contact-imfo-box\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-4 arrow-right\">\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-volume-control-phone\"></i>\n");
      out.write("\t\t\t\t\t<div class=\"overflow-hidden\">\n");
      out.write("\t\t\t\t\t\t<h4>Phone</h4>\n");
      out.write("\t\t\t\t\t\t<p class=\"lead\">\n");
      out.write("\t\t\t\t\t\t\t+01 2000 800 9999\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-4 arrow-right\">\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-envelope\"></i>\n");
      out.write("\t\t\t\t\t<div class=\"overflow-hidden\">\n");
      out.write("\t\t\t\t\t\t<h4>Email</h4>\n");
      out.write("\t\t\t\t\t\t<p class=\"lead\">\n");
      out.write("\t\t\t\t\t\t\thavarecipe@gmail.com\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-map-marker\"></i>\n");
      out.write("\t\t\t\t\t<div class=\"overflow-hidden\">\n");
      out.write("\t\t\t\t\t\t<h4>Location</h4>\n");
      out.write("\t\t\t\t\t\t<p class=\"lead\">\n");
      out.write("\t\t\t\t\t\t\tCCIT FTUI, Depok\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- End Contact info -->\n");
      out.write("\n");
      out.write("\t<!-- Start Footer -->\n");
      out.write("\t<footer class=\"footer-area bg-f\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6\">\n");
      out.write("\t\t\t\t\t<h3>About Us</h3>\n");
      out.write("\t\t\t\t\t<p>Hava Recipe adalah suatu website yang menyediakan resep makanan, mulai dari makanan kecil hingga makanan\n");
      out.write("\t\t\t\t\t\tkhas daerah. Resep yang kami berikan kepada pengunjung mudah dipahami dan di praktekkan. Selain itu, makanan\n");
      out.write("\t\t\t\t\t\tyang kami berikan resepnya itu memenuhi gizi 4 sehat 5 sempurna.</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6\">\n");
      out.write("\t\t\t\t\t<h3>Subscribe</h3>\n");
      out.write("\t\t\t\t\t<div class=\"subscribe_form\">\n");
      out.write("\t\t\t\t\t\t<form class=\"subscribe_form\">\n");
      out.write("\t\t\t\t\t\t\t<input name=\"EMAIL\" id=\"subs-email\" class=\"form_input\" placeholder=\"Email Address...\" type=\"email\">\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"submit\">SUBSCRIBE</button>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6\">\n");
      out.write("\t\t\t\t\t<h3>Contact information</h3>\n");
      out.write("\t\t\t\t\t<p class=\"lead\">CCIT FTUI, Depok</p>\n");
      out.write("\t\t\t\t\t<p class=\"lead\"><a href=\"#\">+01 2000 800 9999</a></p>\n");
      out.write("\t\t\t\t\t<p><a href=\"#\"> havarecipe@gmail.com</a></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"copyright\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t\t\t<p class=\"company-name\">All Rights Reserved. &copy; 2020 <a href=\"#\">Hava Recipes</a> Design By : Hanas Bayu\n");
      out.write("\t\t\t\t\t\t\tPratama and Chelyn Valencia Wardhani </p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</footer>\n");
      out.write("\t<!-- End Footer -->\n");
      out.write("\n");
      out.write("\t<a href=\"#\" id=\"back-to-top\" title=\"Back to top\" style=\"display: none;\"><i class=\"fa fa-paper-plane-o\"\n");
      out.write("\t\t\taria-hidden=\"true\"></i></a>\n");
      out.write("\n");
      out.write("\t<!-- ALL JS FILES -->\n");
      out.write("\t<script src=\"../js/jquery-3.2.1.min.js\"></script>\n");
      out.write("\t<script src=\"../js/popper.min.js\"></script>\n");
      out.write("\t<script src=\"../js/bootstrap.min.js\"></script>\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- ALL PLUGINS -->\n");
      out.write("\t<script src=\"../js/jquery.superslides.min.js\"></script>\n");
      out.write("\t<script src=\"../js/images-loded.min.js\"></script>\n");
      out.write("\t<script src=\"../js/isotope.min.js\"></script>\n");
      out.write("\t<script src=\"../js/baguetteBox.min.js\"></script>\n");
      out.write("\t<script src=\"../js/jquery.mapify.js\"></script>\n");
      out.write("\t<script src=\"../js/form-validator.min.js\"></script>\n");
      out.write("\t<script src=\"../js/contact-form-script.js\"></script>\n");
      out.write("\t<script src=\"../js/custom.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"https://unpkg.com/leaflet@1.6.0/dist/leaflet.js\"></script>\n");
      out.write("\t<script>\n");
      out.write("\t\tvar validationApp = angular.module('validationApp', []);\n");
      out.write("\t\t// create angular controller\n");
      out.write("\t\tvalidationApp.controller('mainController', function ($scope) {\n");
      out.write("\t\t\t// function to submit the form after all validation has occurred\n");
      out.write("\t\t\t$scope.submitForm = function (isValid) {\n");
      out.write("\t\t\t\t// check to make sure the form is completely valid\n");
      out.write("\t\t\t\tif (isValid) {\n");
      out.write("\t\t\t\t\talert('Data Berhasil Disimpan');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t};\n");
      out.write("\t\t});\n");
      out.write("\t\t// koordinat dan zoom view peta\n");
      out.write("\t\t// Koordinat yang digunakan berupa latitude dan longitude,\n");
      out.write("\t\t//sebagai contoh saya menggunakan Koordinat CCIT\n");
      out.write("\t\tvar map = L.map('map').setView([-6.362141, 106.824923], 17);\n");
      out.write("\t\t// ini adalah copyright, bisa dicopot tapi lebih baik kita hargai sang penciptanya ya :)\n");
      out.write("\t\tL.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {\n");
      out.write("\t\t\tattribution: '&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a>',\n");
      out.write("\t\t\tsubdomains: ['a', 'b', 'c'],\n");
      out.write("\t\t}).addTo(map);\n");
      out.write("\t\t// ini adalah koordinat marker\n");
      out.write("\t\tL.marker([-6.362141, 106.824923]).addTo(map)\n");
      out.write("\t\t\t.bindPopup(\"<b>Selamat Datang!</b> Di CCIT FT-UI.\").openPopup();\n");
      out.write("\t\tvar popup = L.popup();\n");
      out.write("\n");
      out.write("\t\tfunction onMapClick(e) {\n");
      out.write("\t\t\tpopup\n");
      out.write("\t\t\t\t.setLatLng(e.latlng)\n");
      out.write("\t\t\t\t.setContent(\"Koordinat pada titik ini adalah \" + e.latlng.toString())\n");
      out.write("\t\t\t\t.openOn(map);\n");
      out.write("\t\t}\n");
      out.write("\t\tmap.on('click', onMapClick);\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("\t<!-- database -->\n");
      out.write("\t<script>\n");
      out.write("\tvar databaseRef = firebase.database().ref('complainmenu/');\n");
      out.write("\tfunction save_user(){\n");
      out.write("\t\tvar nama = document.getElemenById('nama').value;\n");
      out.write("\t\tvar email = document.getElemenById('email').value;\n");
      out.write("\t\tvar menu = document.getElemenById('menu').value;\n");
      out.write("\t\tvar komentar = document.getElemenById('komentar').value;\n");
      out.write("\t\t\n");
      out.write("\t\tvar uid = firebase.database().ref().child('complainmenu').push().key;\n");
      out.write("\t\t\n");
      out.write("\t\tvar data = {\n");
      out.write("\t\t\t\tnama: nama,\n");
      out.write("\t\t\t\temail: email,\n");
      out.write("\t\t\t\tmenu: menu,\n");
      out.write("\t\t\t\tkomentar: komentar\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tvar updates = {};\n");
      out.write("\t\tupdates['/complainmenu/' + uid] = data;\n");
      out.write("\t\tfirebase.database().ref().update(updates);\n");
      out.write("\t\t\n");
      out.write("\t\talert('complain menu has been send!');\n");
      out.write("\t\treload_page();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction reaload_page(){\n");
      out.write("\t\twindow.location.reload();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t</script>\n");
      out.write("\t<!-- database -->\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
